/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApiError */
        ApiError: {
            error: components["schemas"]["ErrorBody"];
        };
        /** ApplyIn */
        ApplyIn: {
            changes: components["schemas"]["SensorEdit"];
            /** Expect Rev */
            expect_rev: {
                [key: string]: number;
            };
            /** Targets */
            targets: string[];
        };
        /** ApplyItemView */
        ApplyItemView: {
            /** Applied */
            applied: ("sensitivity" | "detect_mode" | "zone_enable" | "zone_thresholds" | "subsensor_zones" | "subsensor_timing" | "subsensor_enable" | "dnd")[];
            /** Device Id */
            device_id: string;
            /** Error */
            error: string | null;
            /** Finished At */
            finished_at: number | null;
            /** Mismatched */
            mismatched: ("sensitivity" | "detect_mode" | "zone_enable" | "zone_thresholds" | "subsensor_zones" | "subsensor_timing" | "subsensor_enable" | "dnd")[];
            /** Restore */
            restore: string | null;
            /** Skipped */
            skipped: ("sensitivity" | "detect_mode" | "zone_enable" | "zone_thresholds" | "subsensor_zones" | "subsensor_timing" | "subsensor_enable" | "dnd")[];
            /** Snapshot */
            snapshot: string | null;
            /**
             * State
             * @enum {string}
             */
            state: "queued" | "applying" | "verified" | "partial" | "unverified" | "failed";
        };
        /** ApplyJobView */
        ApplyJobView: {
            /** Apply Id */
            apply_id: string;
            /** Created At */
            created_at: number;
            /** Items */
            items: components["schemas"]["ApplyItemView"][];
            /**
             * Kind
             * @enum {string}
             */
            kind: "apply" | "rollback" | "clone";
            /** Sections */
            sections: ("sensitivity" | "detect_mode" | "zone_enable" | "zone_thresholds" | "subsensor_zones" | "subsensor_timing" | "subsensor_enable" | "dnd")[];
            /** Source */
            source: string | null;
            /**
             * State
             * @enum {string}
             */
            state: "running" | "done";
        };
        /** ApplyMessage */
        ApplyMessage: {
            data: components["schemas"]["ApplyJobView"];
            /** Seq */
            seq: number;
            /** Ts */
            ts: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "apply";
        };
        /** BatchCreate */
        BatchCreate: {
            /**
             * At
             * @default null
             */
            at: string | null;
            /**
             * Delay S
             * @default null
             */
            delay_s: number | null;
            /** Device Ids */
            device_ids: string[];
            /**
             * Presence Override
             * @default false
             */
            presence_override: boolean;
            /**
             * Start
             * @default now
             * @enum {string}
             */
            start: "now" | "delay" | "at";
        };
        /** BatchMessage */
        BatchMessage: {
            data: components["schemas"]["BatchView"];
            /** Seq */
            seq: number;
            /** Ts */
            ts: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "batch";
        };
        /** BatchRetry */
        BatchRetry: {
            /**
             * At
             * @default null
             */
            at: string | null;
            /**
             * Delay S
             * @default null
             */
            delay_s: number | null;
            /**
             * Device Ids
             * @default null
             */
            device_ids: string[] | null;
            /**
             * Start
             * @default now
             * @enum {string}
             */
            start: "now" | "delay" | "at";
        };
        /**
         * BatchState
         * @enum {string}
         */
        BatchState: "waiting" | "running" | "done" | "cancelled";
        /** BatchView */
        BatchView: {
            /** Batch Id */
            batch_id: string;
            /** Created At */
            created_at: number;
            /** Device Ids */
            device_ids: string[];
            /** Expected S */
            expected_s: number;
            /** Fire At */
            fire_at: number;
            /** Jobs */
            jobs: components["schemas"]["CalibrationJobView"][];
            /** Presence Override */
            presence_override: boolean;
            /** Round */
            round: number;
            /** Round Ids */
            round_ids: string[];
            /**
             * Start
             * @enum {string}
             */
            start: "now" | "delay" | "at";
            state: components["schemas"]["BatchState"];
        };
        /** CalibrationHistory */
        CalibrationHistory: {
            /** Device Id */
            device_id: string;
            /** Records */
            records: components["schemas"]["CalibrationRecord"][];
        };
        /** CalibrationJobMessage */
        CalibrationJobMessage: {
            data: components["schemas"]["CalibrationJobView"];
            /** Seq */
            seq: number;
            /** Ts */
            ts: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "calibration_job";
        };
        /** CalibrationJobView */
        CalibrationJobView: {
            /** After */
            after: components["schemas"]["ZonePair"][] | null;
            /** Attempt */
            attempt: number;
            /** Batch Id */
            batch_id: string;
            /** Before */
            before: components["schemas"]["ZonePair"][] | null;
            /** Detail */
            detail: string;
            /** Device Id */
            device_id: string;
            /** Elapsed S */
            elapsed_s: number | null;
            /** Error */
            error: string | null;
            /** History Saved */
            history_saved: boolean;
            /** Retryable */
            retryable: boolean;
            /** Started */
            started: boolean;
            state: components["schemas"]["CalibrationState"];
        };
        /** CalibrationRecord */
        CalibrationRecord: {
            /** Detect Mode */
            detect_mode: number | null;
            /** Device Name */
            device_name: string | null;
            /** Sensitivity */
            sensitivity: number | null;
            /** Timestamp */
            timestamp: string;
            /** Zones */
            zones: components["schemas"]["CalibrationZone"][];
        };
        /**
         * CalibrationState
         * @enum {string}
         */
        CalibrationState: "idle" | "starting" | "learning" | "succeeded" | "failed" | "lost" | "timeout" | "cancelled";
        /** CalibrationSummary */
        CalibrationSummary: {
            /** Detect Mode */
            detect_mode: number | null;
            /** Sensitivity */
            sensitivity: number | null;
            /** Timestamp */
            timestamp: string;
        };
        /** CalibrationZone */
        CalibrationZone: {
            /** Distance M */
            distance_m: number | null;
            /** Index */
            index: number;
            /** Maintain */
            maintain: number;
            /** Trigger */
            trigger: number;
        };
        /** Change */
        Change: {
            /** After */
            after: boolean | number | number[] | null;
            /** Before */
            before: boolean | number | number[] | null;
            /** Index */
            index: number | null;
            /**
             * Part
             * @enum {string}
             */
            part: "value" | "trigger" | "maintain" | "presence_s" | "absence_s";
            /** Risks */
            risks: ("absolute_overwrite" | "large_change" | "beyond_ui_range" | "zone_off" | "subsensor_off" | "subsensor_no_zone" | "sensitivity_only" | "dnd_on" | "learning_skipped")[];
            /**
             * Section
             * @enum {string}
             */
            section: "sensitivity" | "detect_mode" | "zone_enable" | "zone_thresholds" | "subsensor_zones" | "subsensor_timing" | "subsensor_enable" | "dnd";
        };
        /** ClientMessage */
        ClientMessage: components["schemas"]["LiveSubscribeMessage"] | components["schemas"]["LiveUnsubscribeMessage"];
        /** CloneApplyIn */
        CloneApplyIn: {
            /** Expect Rev */
            expect_rev: {
                [key: string]: number;
            };
            /** Sections */
            sections: ("sensitivity" | "detect_mode" | "zone_enable" | "zone_thresholds" | "subsensor_zones" | "subsensor_timing" | "subsensor_enable" | "dnd")[];
            /** Source */
            source: string;
            /** Targets */
            targets: string[];
        };
        /** CloneIn */
        CloneIn: {
            /**
             * Expect Rev
             * @default null
             */
            expect_rev: {
                [key: string]: number;
            } | null;
            /** Sections */
            sections: ("sensitivity" | "detect_mode" | "zone_enable" | "zone_thresholds" | "subsensor_zones" | "subsensor_timing" | "subsensor_enable" | "dnd")[];
            /** Source */
            source: string;
            /** Targets */
            targets: string[];
        };
        /** ConfigView */
        ConfigView: {
            /** Config Rev */
            config_rev: number;
            /** Device Id */
            device_id: string;
            /** Distances M */
            distances_m: number[];
            profile: components["schemas"]["ProfileView"];
            /** Read At */
            read_at: number;
        };
        /** ConnectingDevice */
        ConnectingDevice: {
            /** Address */
            address: string;
            /** Since */
            since: number;
        };
        /** Countdown */
        Countdown: {
            /** Batch Id */
            batch_id: string;
            /** Fire At */
            fire_at: number;
            /** Remaining S */
            remaining_s: number;
        };
        /** CountdownMessage */
        CountdownMessage: {
            data: components["schemas"]["Countdown"];
            /**
             * Seq
             * @default null
             */
            seq: null;
            /** Ts */
            ts: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "countdown";
        };
        /** DeviceHistory */
        DeviceHistory: {
            /** Detail */
            detail: boolean;
            /** Device Id */
            device_id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "presence" | "light";
            /** Light */
            light: components["schemas"]["LightRecordView"][];
            /** Presence */
            presence: components["schemas"]["PresenceRecordView"][];
            /** Read At */
            read_at: number;
        };
        /** DraftIn */
        DraftIn: {
            changes: components["schemas"]["SensorEdit"];
            /**
             * Expect Rev
             * @default null
             */
            expect_rev: {
                [key: string]: number;
            } | null;
            /** Targets */
            targets: string[];
        };
        /** DraftPreview */
        DraftPreview: {
            /** Checked At */
            checked_at: number;
            /** Items */
            items: components["schemas"]["SensorPreview"][];
            /**
             * Kind
             * @enum {string}
             */
            kind: "apply" | "rollback" | "clone";
            /** Risks */
            risks: ("absolute_overwrite" | "large_change" | "beyond_ui_range" | "zone_off" | "subsensor_off" | "subsensor_no_zone" | "sensitivity_only" | "dnd_on" | "learning_skipped")[];
            /** Source Rev */
            source_rev: number | null;
        };
        /** ErrorBody */
        ErrorBody: {
            /**
             * Code
             * @enum {string}
             */
            code: "unauthorized" | "forbidden_origin" | "not_found" | "already_exists" | "busy" | "not_connected" | "invalid" | "invalid_request" | "invalid_file" | "storage" | "internal" | "batch_active" | "apply_active" | "stale" | "device_error";
            /** Message */
            message: string;
        };
        /** GatherMessage */
        GatherMessage: {
            data: components["schemas"]["GatherStatus"];
            /** Seq */
            seq: number;
            /** Ts */
            ts: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "gather";
        };
        /** GatherStatus */
        GatherStatus: {
            /** Connecting */
            connecting: components["schemas"]["ConnectingDevice"][];
            /** Gathering */
            gathering: boolean;
        };
        /** Health */
        Health: {
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
            /** Version */
            version: string;
        };
        /** ImportResult */
        ImportResult: {
            /** Added */
            added: components["schemas"]["PendingView"][];
            /** Site Id */
            site_id: string;
        };
        /** LightRecordView */
        LightRecordView: {
            /** Index */
            index: number;
            /** Light Lux */
            light_lux: number;
            /** Timestamp */
            timestamp: number;
        };
        /**
         * LinkState
         * @enum {string}
         */
        LinkState: "disconnected" | "connecting" | "connected" | "lost";
        /** LiveData */
        LiveData: {
            /** At */
            at: number;
            /** Device Id */
            device_id: string;
            /** Pir */
            pir: boolean | null;
            /** Sub Sensor Presence */
            sub_sensor_presence: boolean[];
            /** Zones */
            zones: components["schemas"]["LiveZone"][];
        };
        /** LiveInfo */
        LiveInfo: {
            /** Address */
            address: string;
            /** Battery Pct */
            battery_pct: number | null;
            /** Busy */
            busy: string | null;
            /** Firmware */
            firmware: string | null;
            /** Gathered At */
            gathered_at: number;
            /** Light Lux */
            light_lux: number | null;
            link: components["schemas"]["LinkState"];
            /** Lost Reason */
            lost_reason: string;
            /** Name */
            name: string | null;
        };
        /** LiveMessage */
        LiveMessage: {
            data: components["schemas"]["LiveData"];
            /**
             * Seq
             * @default null
             */
            seq: null;
            /** Ts */
            ts: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "live";
        };
        /** LiveSubscribeMessage */
        LiveSubscribeMessage: {
            data: components["schemas"]["LiveWatch"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "live_subscribe";
        };
        /** LiveUnsubscribeMessage */
        LiveUnsubscribeMessage: {
            data: components["schemas"]["LiveWatch"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "live_unsubscribe";
        };
        /** LiveWatch */
        LiveWatch: {
            /** Device Ids */
            device_ids: string[];
        };
        /** LiveZone */
        LiveZone: {
            /** Distance M */
            distance_m: number;
            /** Enabled */
            enabled: boolean;
            /** Index */
            index: number;
            /** Maintain */
            maintain: number;
            /** Maintain Threshold */
            maintain_threshold: number;
            /** Trigger */
            trigger: number;
            /** Trigger Active */
            trigger_active: boolean;
            /** Trigger Threshold */
            trigger_threshold: number;
        };
        /** Notice */
        Notice: {
            /** Address */
            address: string | null;
            /** At */
            at: number;
            /**
             * Code
             * @enum {string}
             */
            code: "gather_failed" | "internal";
            /** Device Id */
            device_id: string | null;
            /**
             * Level
             * @enum {string}
             */
            level: "info" | "warning" | "error";
            /** Message */
            message: string;
            /** Name */
            name: string | null;
        };
        /** NoticeMessage */
        NoticeMessage: {
            data: components["schemas"]["Notice"];
            /** Seq */
            seq: number;
            /** Ts */
            ts: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "notice";
        };
        /** PendingData */
        PendingData: {
            /** Pending */
            pending: components["schemas"]["PendingView"][];
        };
        /** PendingMessage */
        PendingMessage: {
            data: components["schemas"]["PendingData"];
            /** Seq */
            seq: number;
            /** Ts */
            ts: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "pending";
        };
        /** PendingView */
        PendingView: {
            /** Address */
            address: string;
            /** Alias */
            alias: string;
            /** Site Id */
            site_id: string;
            /** Source */
            source: string;
        };
        /** PreflightRequest */
        PreflightRequest: {
            /** Device Ids */
            device_ids: string[];
            /**
             * Window S
             * @default 3
             */
            window_s: number;
        };
        /** PreflightResult */
        PreflightResult: {
            /** Checked At */
            checked_at: number;
            /** Results */
            results: components["schemas"]["PresenceView"][];
        };
        /** PresenceRecordView */
        PresenceRecordView: {
            /** Index */
            index: number;
            /** Sensor Presence */
            sensor_presence: boolean[];
            /** Sub Sensor Triggers */
            sub_sensor_triggers: number[];
            /** Timestamp */
            timestamp: number;
            /** Zone Enabled */
            zone_enabled: boolean[];
            /** Zone Presence */
            zone_presence: boolean[];
            /** Zone Triggers */
            zone_triggers: number[];
        };
        /** PresenceView */
        PresenceView: {
            /** Device Id */
            device_id: string;
            /** Error */
            error: string | null;
            /** Occupied */
            occupied: boolean | null;
            /** Pir */
            pir: boolean | null;
            /** Presence */
            presence: boolean | null;
            /** Samples */
            samples: number;
        };
        /** ProfileView */
        ProfileView: {
            /** Detect Mode */
            detect_mode: number;
            /** Dnd */
            dnd: boolean | null;
            /** Sensitivity */
            sensitivity: number;
            /** Subsensor Enable */
            subsensor_enable: boolean[];
            /** Subsensor Timing */
            subsensor_timing: [
                number,
                number
            ][];
            /** Subsensor Zones */
            subsensor_zones: number[][];
            /** Zone Enable */
            zone_enable: boolean[];
            /** Zone Thresholds */
            zone_thresholds: components["schemas"]["ZonePair"][];
        };
        /** RegistryInfo */
        RegistryInfo: {
            /** Alias */
            alias: string;
            /** Battery Pct */
            battery_pct: number | null;
            /** Last Seen */
            last_seen: string | null;
            /** Location */
            location: string;
            /** Notes */
            notes: string;
            /** Site Id */
            site_id: string;
        };
        /** ReleaseRequest */
        ReleaseRequest: {
            /**
             * Device Ids
             * @default null
             */
            device_ids: string[] | null;
        };
        /** RollbackApplyIn */
        RollbackApplyIn: {
            /** Expect Rev */
            expect_rev: {
                [key: string]: number;
            };
            /** Items */
            items: components["schemas"]["RollbackItem"][];
        };
        /** RollbackIn */
        RollbackIn: {
            /**
             * Expect Rev
             * @default null
             */
            expect_rev: {
                [key: string]: number;
            } | null;
            /** Items */
            items: components["schemas"]["RollbackItem"][];
        };
        /** RollbackItem */
        RollbackItem: {
            /** Device Id */
            device_id: string;
            /** Snapshot */
            snapshot: string;
        };
        /** SensorCreate */
        SensorCreate: {
            /** Alias */
            alias: string;
            /** Device Id */
            device_id: string;
            /**
             * Location
             * @default
             */
            location: string;
            /**
             * Notes
             * @default
             */
            notes: string;
            /** Site Id */
            site_id: string;
        };
        /** SensorEdit */
        SensorEdit: {
            /**
             * Dnd
             * @default null
             */
            dnd: boolean | null;
            /**
             * Sensitivity
             * @default null
             */
            sensitivity: number | null;
            /**
             * Subsensor Enable
             * @default null
             */
            subsensor_enable: boolean[] | null;
            /**
             * Subsensor Timing
             * @default null
             */
            subsensor_timing: [
                number,
                number
            ][] | null;
            /**
             * Subsensor Zones
             * @default null
             */
            subsensor_zones: number[][] | null;
            /**
             * Zone Enable
             * @default null
             */
            zone_enable: boolean[] | null;
            /** @default null */
            zone_thresholds: components["schemas"]["ThresholdEdit"] | null;
        };
        /** SensorInfoImport */
        SensorInfoImport: {
            /** Content */
            content: string;
            /** Filename */
            filename: string;
            /**
             * Site Id
             * @default null
             */
            site_id: string | null;
            /**
             * Site Name
             * @default null
             */
            site_name: string | null;
        };
        /** SensorMessage */
        SensorMessage: {
            data: components["schemas"]["SensorView"];
            /** Seq */
            seq: number;
            /** Ts */
            ts: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "sensor";
        };
        /** SensorPreview */
        SensorPreview: {
            after: components["schemas"]["ProfileView"] | null;
            before: components["schemas"]["ProfileView"] | null;
            /** Changes */
            changes: components["schemas"]["Change"][];
            /** Config Rev */
            config_rev: number;
            /** Device Id */
            device_id: string;
            /** Error */
            error: string | null;
            /** Risks */
            risks: ("absolute_overwrite" | "large_change" | "beyond_ui_range" | "zone_off" | "subsensor_off" | "subsensor_no_zone" | "sensitivity_only" | "dnd_on" | "learning_skipped")[];
        };
        /** SensorRemoved */
        SensorRemoved: {
            /** Device Id */
            device_id: string;
        };
        /** SensorRemovedMessage */
        SensorRemovedMessage: {
            data: components["schemas"]["SensorRemoved"];
            /** Seq */
            seq: number;
            /** Ts */
            ts: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "sensor_removed";
        };
        /** SensorUpdate */
        SensorUpdate: {
            /**
             * Alias
             * @default null
             */
            alias: string | null;
            /**
             * Location
             * @default null
             */
            location: string | null;
            /**
             * Notes
             * @default null
             */
            notes: string | null;
            /**
             * Site Id
             * @default null
             */
            site_id: string | null;
        };
        /** SensorView */
        SensorView: {
            /** Config Rev */
            config_rev: number;
            /** Device Id */
            device_id: string;
            last_calibration: components["schemas"]["CalibrationSummary"] | null;
            last_snapshot: components["schemas"]["SnapshotSummary"] | null;
            live: components["schemas"]["LiveInfo"] | null;
            registry: components["schemas"]["RegistryInfo"] | null;
        };
        /** ServerInfo */
        ServerInfo: {
            /** Lan */
            lan: boolean;
            sim: components["schemas"]["SimInfo"] | null;
            /** Version */
            version: string;
        };
        /** ServerMessage */
        ServerMessage: components["schemas"]["SnapshotMessage"] | components["schemas"]["SensorMessage"] | components["schemas"]["SensorRemovedMessage"] | components["schemas"]["SitesMessage"] | components["schemas"]["PendingMessage"] | components["schemas"]["GatherMessage"] | components["schemas"]["NoticeMessage"] | components["schemas"]["BatchMessage"] | components["schemas"]["CalibrationJobMessage"] | components["schemas"]["LiveMessage"] | components["schemas"]["CountdownMessage"] | components["schemas"]["ApplyMessage"];
        /** SimInfo */
        SimInfo: {
            /** Count */
            count: number;
            /** Speed */
            speed: number;
        };
        /** SiteCreate */
        SiteCreate: {
            /** Name */
            name: string;
            /**
             * Site Id
             * @default null
             */
            site_id: string | null;
        };
        /** SiteView */
        SiteView: {
            /** Name */
            name: string;
            /** Site Id */
            site_id: string;
        };
        /** SitesData */
        SitesData: {
            /** Sites */
            sites: components["schemas"]["SiteView"][];
        };
        /** SitesMessage */
        SitesMessage: {
            data: components["schemas"]["SitesData"];
            /** Seq */
            seq: number;
            /** Ts */
            ts: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "sites";
        };
        /** SnapshotDetail */
        SnapshotDetail: {
            /** Device Id */
            device_id: string;
            profile: components["schemas"]["ProfileView"];
            snapshot: components["schemas"]["SnapshotView"];
        };
        /** SnapshotList */
        SnapshotList: {
            /** Device Id */
            device_id: string;
            /** Snapshots */
            snapshots: components["schemas"]["SnapshotView"][];
        };
        /** SnapshotMessage */
        SnapshotMessage: {
            data: components["schemas"]["StateSnapshot"];
            /** Seq */
            seq: number;
            /** Ts */
            ts: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "snapshot";
        };
        /** SnapshotSummary */
        SnapshotSummary: {
            /** Name */
            name: string;
            /** Reason */
            reason: string;
            /** Taken At */
            taken_at: string;
        };
        /** SnapshotView */
        SnapshotView: {
            /** Name */
            name: string;
            /** Reason */
            reason: string;
            /** Sections */
            sections: string[];
            /** Taken At */
            taken_at: string;
        };
        /** StateSnapshot */
        StateSnapshot: {
            apply: components["schemas"]["ApplyJobView"] | null;
            batch: components["schemas"]["BatchView"] | null;
            gather: components["schemas"]["GatherStatus"];
            /** Pending */
            pending: components["schemas"]["PendingView"][];
            /** Sensors */
            sensors: components["schemas"]["SensorView"][];
            /** Seq */
            seq: number;
            server: components["schemas"]["ServerInfo"];
            /** Sites */
            sites: components["schemas"]["SiteView"][];
        };
        /** ThresholdEdit */
        ThresholdEdit: {
            /** Maintain */
            maintain: (number | null)[];
            /**
             * Mode
             * @enum {string}
             */
            mode: "relative" | "absolute";
            /** Trigger */
            trigger: (number | null)[];
        };
        /** TimeSyncIn */
        TimeSyncIn: {
            /** Device Ids */
            device_ids: string[];
        };
        /** TimeSyncItem */
        TimeSyncItem: {
            /** Device Id */
            device_id: string;
            /** Error */
            error: string | null;
            /** Written At */
            written_at: number | null;
        };
        /** TimeSyncResult */
        TimeSyncResult: {
            /** Items */
            items: components["schemas"]["TimeSyncItem"][];
        };
        /** ZonePair */
        ZonePair: {
            /** Maintain */
            maintain: number;
            /** Trigger */
            trigger: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
