/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApiError */
        ApiError: {
            error: components["schemas"]["ErrorBody"];
        };
        /** BatchCreate */
        BatchCreate: {
            /**
             * At
             * @default null
             */
            at: string | null;
            /**
             * Delay S
             * @default null
             */
            delay_s: number | null;
            /** Device Ids */
            device_ids: string[];
            /**
             * Presence Override
             * @default false
             */
            presence_override: boolean;
            /**
             * Start
             * @default now
             * @enum {string}
             */
            start: "now" | "delay" | "at";
        };
        /** BatchMessage */
        BatchMessage: {
            data: components["schemas"]["BatchView"];
            /** Seq */
            seq: number;
            /** Ts */
            ts: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "batch";
        };
        /** BatchRetry */
        BatchRetry: {
            /**
             * At
             * @default null
             */
            at: string | null;
            /**
             * Delay S
             * @default null
             */
            delay_s: number | null;
            /**
             * Device Ids
             * @default null
             */
            device_ids: string[] | null;
            /**
             * Start
             * @default now
             * @enum {string}
             */
            start: "now" | "delay" | "at";
        };
        /**
         * BatchState
         * @enum {string}
         */
        BatchState: "waiting" | "running" | "done" | "cancelled";
        /** BatchView */
        BatchView: {
            /** Batch Id */
            batch_id: string;
            /** Created At */
            created_at: number;
            /** Device Ids */
            device_ids: string[];
            /** Expected S */
            expected_s: number;
            /** Fire At */
            fire_at: number;
            /** Jobs */
            jobs: components["schemas"]["CalibrationJobView"][];
            /** Presence Override */
            presence_override: boolean;
            /** Round */
            round: number;
            /** Round Ids */
            round_ids: string[];
            /**
             * Start
             * @enum {string}
             */
            start: "now" | "delay" | "at";
            state: components["schemas"]["BatchState"];
        };
        /** CalibrationJobMessage */
        CalibrationJobMessage: {
            data: components["schemas"]["CalibrationJobView"];
            /** Seq */
            seq: number;
            /** Ts */
            ts: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "calibration_job";
        };
        /** CalibrationJobView */
        CalibrationJobView: {
            /** After */
            after: components["schemas"]["ZonePair"][] | null;
            /** Attempt */
            attempt: number;
            /** Batch Id */
            batch_id: string;
            /** Before */
            before: components["schemas"]["ZonePair"][] | null;
            /** Detail */
            detail: string;
            /** Device Id */
            device_id: string;
            /** Elapsed S */
            elapsed_s: number | null;
            /** Error */
            error: string | null;
            /** History Saved */
            history_saved: boolean;
            /** Retryable */
            retryable: boolean;
            /** Started */
            started: boolean;
            state: components["schemas"]["CalibrationState"];
        };
        /**
         * CalibrationState
         * @enum {string}
         */
        CalibrationState: "idle" | "starting" | "learning" | "succeeded" | "failed" | "lost" | "timeout" | "cancelled";
        /** CalibrationSummary */
        CalibrationSummary: {
            /** Detect Mode */
            detect_mode: number | null;
            /** Sensitivity */
            sensitivity: number | null;
            /** Timestamp */
            timestamp: string;
        };
        /** ClientMessage */
        ClientMessage: components["schemas"]["LiveSubscribeMessage"] | components["schemas"]["LiveUnsubscribeMessage"];
        /** ConnectingDevice */
        ConnectingDevice: {
            /** Address */
            address: string;
            /** Since */
            since: number;
        };
        /** Countdown */
        Countdown: {
            /** Batch Id */
            batch_id: string;
            /** Fire At */
            fire_at: number;
            /** Remaining S */
            remaining_s: number;
        };
        /** CountdownMessage */
        CountdownMessage: {
            data: components["schemas"]["Countdown"];
            /**
             * Seq
             * @default null
             */
            seq: null;
            /** Ts */
            ts: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "countdown";
        };
        /** ErrorBody */
        ErrorBody: {
            /**
             * Code
             * @enum {string}
             */
            code: "unauthorized" | "forbidden_origin" | "not_found" | "already_exists" | "busy" | "not_connected" | "invalid" | "invalid_request" | "invalid_file" | "storage" | "internal" | "batch_active";
            /** Message */
            message: string;
        };
        /** GatherMessage */
        GatherMessage: {
            data: components["schemas"]["GatherStatus"];
            /** Seq */
            seq: number;
            /** Ts */
            ts: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "gather";
        };
        /** GatherStatus */
        GatherStatus: {
            /** Connecting */
            connecting: components["schemas"]["ConnectingDevice"][];
            /** Gathering */
            gathering: boolean;
        };
        /** Health */
        Health: {
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
            /** Version */
            version: string;
        };
        /** ImportResult */
        ImportResult: {
            /** Added */
            added: components["schemas"]["PendingView"][];
            /** Site Id */
            site_id: string;
        };
        /**
         * LinkState
         * @enum {string}
         */
        LinkState: "disconnected" | "connecting" | "connected" | "lost";
        /** LiveData */
        LiveData: {
            /** At */
            at: number;
            /** Device Id */
            device_id: string;
            /** Pir */
            pir: boolean | null;
            /** Sub Sensor Presence */
            sub_sensor_presence: boolean[];
            /** Zones */
            zones: components["schemas"]["LiveZone"][];
        };
        /** LiveInfo */
        LiveInfo: {
            /** Address */
            address: string;
            /** Battery Pct */
            battery_pct: number | null;
            /** Busy */
            busy: string | null;
            /** Firmware */
            firmware: string | null;
            /** Gathered At */
            gathered_at: number;
            /** Light Lux */
            light_lux: number | null;
            link: components["schemas"]["LinkState"];
            /** Lost Reason */
            lost_reason: string;
            /** Name */
            name: string | null;
        };
        /** LiveMessage */
        LiveMessage: {
            data: components["schemas"]["LiveData"];
            /**
             * Seq
             * @default null
             */
            seq: null;
            /** Ts */
            ts: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "live";
        };
        /** LiveSubscribeMessage */
        LiveSubscribeMessage: {
            data: components["schemas"]["LiveWatch"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "live_subscribe";
        };
        /** LiveUnsubscribeMessage */
        LiveUnsubscribeMessage: {
            data: components["schemas"]["LiveWatch"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "live_unsubscribe";
        };
        /** LiveWatch */
        LiveWatch: {
            /** Device Ids */
            device_ids: string[];
        };
        /** LiveZone */
        LiveZone: {
            /** Distance M */
            distance_m: number;
            /** Enabled */
            enabled: boolean;
            /** Index */
            index: number;
            /** Maintain */
            maintain: number;
            /** Maintain Threshold */
            maintain_threshold: number;
            /** Trigger */
            trigger: number;
            /** Trigger Active */
            trigger_active: boolean;
            /** Trigger Threshold */
            trigger_threshold: number;
        };
        /** Notice */
        Notice: {
            /** Address */
            address: string | null;
            /** At */
            at: number;
            /**
             * Code
             * @enum {string}
             */
            code: "gather_failed" | "internal";
            /** Device Id */
            device_id: string | null;
            /**
             * Level
             * @enum {string}
             */
            level: "info" | "warning" | "error";
            /** Message */
            message: string;
            /** Name */
            name: string | null;
        };
        /** NoticeMessage */
        NoticeMessage: {
            data: components["schemas"]["Notice"];
            /** Seq */
            seq: number;
            /** Ts */
            ts: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "notice";
        };
        /** PendingData */
        PendingData: {
            /** Pending */
            pending: components["schemas"]["PendingView"][];
        };
        /** PendingMessage */
        PendingMessage: {
            data: components["schemas"]["PendingData"];
            /** Seq */
            seq: number;
            /** Ts */
            ts: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "pending";
        };
        /** PendingView */
        PendingView: {
            /** Address */
            address: string;
            /** Alias */
            alias: string;
            /** Site Id */
            site_id: string;
            /** Source */
            source: string;
        };
        /** PreflightRequest */
        PreflightRequest: {
            /** Device Ids */
            device_ids: string[];
            /**
             * Window S
             * @default 3
             */
            window_s: number;
        };
        /** PreflightResult */
        PreflightResult: {
            /** Checked At */
            checked_at: number;
            /** Results */
            results: components["schemas"]["PresenceView"][];
        };
        /** PresenceView */
        PresenceView: {
            /** Device Id */
            device_id: string;
            /** Error */
            error: string | null;
            /** Occupied */
            occupied: boolean | null;
            /** Pir */
            pir: boolean | null;
            /** Presence */
            presence: boolean | null;
            /** Samples */
            samples: number;
        };
        /** RegistryInfo */
        RegistryInfo: {
            /** Alias */
            alias: string;
            /** Battery Pct */
            battery_pct: number | null;
            /** Last Seen */
            last_seen: string | null;
            /** Location */
            location: string;
            /** Notes */
            notes: string;
            /** Site Id */
            site_id: string;
        };
        /** ReleaseRequest */
        ReleaseRequest: {
            /**
             * Device Ids
             * @default null
             */
            device_ids: string[] | null;
        };
        /** SensorCreate */
        SensorCreate: {
            /** Alias */
            alias: string;
            /** Device Id */
            device_id: string;
            /**
             * Location
             * @default
             */
            location: string;
            /**
             * Notes
             * @default
             */
            notes: string;
            /** Site Id */
            site_id: string;
        };
        /** SensorInfoImport */
        SensorInfoImport: {
            /** Content */
            content: string;
            /** Filename */
            filename: string;
            /**
             * Site Id
             * @default null
             */
            site_id: string | null;
            /**
             * Site Name
             * @default null
             */
            site_name: string | null;
        };
        /** SensorMessage */
        SensorMessage: {
            data: components["schemas"]["SensorView"];
            /** Seq */
            seq: number;
            /** Ts */
            ts: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "sensor";
        };
        /** SensorRemoved */
        SensorRemoved: {
            /** Device Id */
            device_id: string;
        };
        /** SensorRemovedMessage */
        SensorRemovedMessage: {
            data: components["schemas"]["SensorRemoved"];
            /** Seq */
            seq: number;
            /** Ts */
            ts: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "sensor_removed";
        };
        /** SensorUpdate */
        SensorUpdate: {
            /**
             * Alias
             * @default null
             */
            alias: string | null;
            /**
             * Location
             * @default null
             */
            location: string | null;
            /**
             * Notes
             * @default null
             */
            notes: string | null;
            /**
             * Site Id
             * @default null
             */
            site_id: string | null;
        };
        /** SensorView */
        SensorView: {
            /** Device Id */
            device_id: string;
            last_calibration: components["schemas"]["CalibrationSummary"] | null;
            last_snapshot: components["schemas"]["SnapshotSummary"] | null;
            live: components["schemas"]["LiveInfo"] | null;
            registry: components["schemas"]["RegistryInfo"] | null;
        };
        /** ServerInfo */
        ServerInfo: {
            /** Lan */
            lan: boolean;
            sim: components["schemas"]["SimInfo"] | null;
            /** Version */
            version: string;
        };
        /** ServerMessage */
        ServerMessage: components["schemas"]["SnapshotMessage"] | components["schemas"]["SensorMessage"] | components["schemas"]["SensorRemovedMessage"] | components["schemas"]["SitesMessage"] | components["schemas"]["PendingMessage"] | components["schemas"]["GatherMessage"] | components["schemas"]["NoticeMessage"] | components["schemas"]["BatchMessage"] | components["schemas"]["CalibrationJobMessage"] | components["schemas"]["LiveMessage"] | components["schemas"]["CountdownMessage"];
        /** SimInfo */
        SimInfo: {
            /** Count */
            count: number;
            /** Speed */
            speed: number;
        };
        /** SiteCreate */
        SiteCreate: {
            /** Name */
            name: string;
            /**
             * Site Id
             * @default null
             */
            site_id: string | null;
        };
        /** SiteView */
        SiteView: {
            /** Name */
            name: string;
            /** Site Id */
            site_id: string;
        };
        /** SitesData */
        SitesData: {
            /** Sites */
            sites: components["schemas"]["SiteView"][];
        };
        /** SitesMessage */
        SitesMessage: {
            data: components["schemas"]["SitesData"];
            /** Seq */
            seq: number;
            /** Ts */
            ts: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "sites";
        };
        /** SnapshotMessage */
        SnapshotMessage: {
            data: components["schemas"]["StateSnapshot"];
            /** Seq */
            seq: number;
            /** Ts */
            ts: number;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "snapshot";
        };
        /** SnapshotSummary */
        SnapshotSummary: {
            /** Name */
            name: string;
            /** Reason */
            reason: string;
            /** Taken At */
            taken_at: string;
        };
        /** StateSnapshot */
        StateSnapshot: {
            batch: components["schemas"]["BatchView"] | null;
            gather: components["schemas"]["GatherStatus"];
            /** Pending */
            pending: components["schemas"]["PendingView"][];
            /** Sensors */
            sensors: components["schemas"]["SensorView"][];
            /** Seq */
            seq: number;
            server: components["schemas"]["ServerInfo"];
            /** Sites */
            sites: components["schemas"]["SiteView"][];
        };
        /** ZonePair */
        ZonePair: {
            /** Maintain */
            maintain: number;
            /** Trigger */
            trigger: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
