import type { components } from './schema'

type S = components['schemas']

export type LinkState = S['LinkState']
export type SiteView = S['SiteView']
export type RegistryInfo = S['RegistryInfo']
export type LiveInfo = S['LiveInfo']
export type CalibrationSummary = S['CalibrationSummary']
export type SnapshotSummary = S['SnapshotSummary']
export type SensorView = S['SensorView']
export type PendingView = S['PendingView']
export type ConnectingDevice = S['ConnectingDevice']
export type GatherStatus = S['GatherStatus']
export type SimInfo = S['SimInfo']
export type ServerInfo = S['ServerInfo']
export type StateSnapshot = S['StateSnapshot']
export type ImportResult = S['ImportResult']
export type ErrorCode = S['ErrorBody']['code']
export type ApiError = S['ApiError']
export type Notice = S['Notice']
export type ServerMessage = S['ServerMessage']

export type SiteCreate = S['SiteCreate']
export type SensorCreate = S['SensorCreate']
export type SensorUpdate = S['SensorUpdate']
export type ReleaseRequest = S['ReleaseRequest']
export type SensorInfoImport = S['SensorInfoImport']

// -- M3 (docs/GUI_API.md 14.4) ------------------------------------------------------
export type LiveData = S['LiveData']
export type LiveZone = S['LiveZone']
export type Countdown = S['Countdown']
export type PresenceView = S['PresenceView']
export type PreflightResult = S['PreflightResult']
export type BatchView = S['BatchView']
export type CalibrationJobView = S['CalibrationJobView']
export type ZonePair = S['ZonePair']
export type CalibrationState = S['CalibrationState']
export type BatchState = S['BatchState']
export type ClientMessage = S['ClientMessage']
export type PreflightRequest = S['PreflightRequest']
export type BatchCreate = S['BatchCreate']
export type BatchRetry = S['BatchRetry']
export type StartMode = BatchCreate['start']
