import type { components } from './schema'

type S = components['schemas']

export type LinkState = S['LinkState']
export type SiteView = S['SiteView']
export type RegistryInfo = S['RegistryInfo']
export type LiveInfo = S['LiveInfo']
export type CalibrationSummary = S['CalibrationSummary']
export type SnapshotSummary = S['SnapshotSummary']
export type SensorView = S['SensorView']
export type PendingView = S['PendingView']
export type ConnectingDevice = S['ConnectingDevice']
export type GatherStatus = S['GatherStatus']
export type SimInfo = S['SimInfo']
export type ServerInfo = S['ServerInfo']
export type StateSnapshot = S['StateSnapshot']
export type ImportResult = S['ImportResult']
export type ErrorCode = S['ErrorBody']['code']
export type ApiError = S['ApiError']
export type Notice = S['Notice']
export type ServerMessage = S['ServerMessage']

export type SiteCreate = S['SiteCreate']
export type SensorCreate = S['SensorCreate']
export type SensorUpdate = S['SensorUpdate']
export type ReleaseRequest = S['ReleaseRequest']
export type SensorInfoImport = S['SensorInfoImport']

// -- M3 (docs/GUI_API.md 14.4) ------------------------------------------------------
export type LiveData = S['LiveData']
export type LiveZone = S['LiveZone']
export type Countdown = S['Countdown']
export type PresenceView = S['PresenceView']
export type PreflightResult = S['PreflightResult']
export type BatchView = S['BatchView']
export type CalibrationJobView = S['CalibrationJobView']
export type ZonePair = S['ZonePair']
export type CalibrationState = S['CalibrationState']
export type BatchState = S['BatchState']
export type ClientMessage = S['ClientMessage']
export type PreflightRequest = S['PreflightRequest']
export type BatchCreate = S['BatchCreate']
export type BatchRetry = S['BatchRetry']
export type StartMode = BatchCreate['start']

// -- M4 (docs/GUI_API.md 15.4 (6)) ----------------------------------------------------------
export type ProfileView = S['ProfileView']
export type ConfigView = S['ConfigView']
export type ThresholdEdit = S['ThresholdEdit']
export type SensorEdit = S['SensorEdit']
export type DraftIn = S['DraftIn']
export type ApplyIn = S['ApplyIn']
export type RollbackIn = S['RollbackIn']
export type RollbackApplyIn = S['RollbackApplyIn']
export type RollbackItem = S['RollbackItem']
export type CloneIn = S['CloneIn']
export type CloneApplyIn = S['CloneApplyIn']
export type Change = S['Change']
export type SensorPreview = S['SensorPreview']
export type DraftPreview = S['DraftPreview']
export type ApplyItemView = S['ApplyItemView']
export type ApplyJobView = S['ApplyJobView']
export type TimeSyncResult = S['TimeSyncResult']
export type TimeSyncItem = S['TimeSyncItem']
export type CalibrationRecord = S['CalibrationRecord']
export type CalibrationHistory = S['CalibrationHistory']
export type SnapshotView = S['SnapshotView']
export type SnapshotList = S['SnapshotList']
export type SnapshotDetail = S['SnapshotDetail']
export type DeviceHistory = S['DeviceHistory']
export type PresenceRecordView = S['PresenceRecordView']
export type LightRecordView = S['LightRecordView']
export type Section = Change['section']
export type RiskCode = Change['risks'][number]
export type ApplyKind = ApplyJobView['kind']
export type ApplyItemState = ApplyItemView['state']
export type DeviceHistoryKind = DeviceHistory['kind']
