// Every Korean UI string lives here (D15, docs/GUI_API.md 10.2).
import type { ErrorCode } from './api/types'

export const t = {
  link: {
    connected: '연결됨',
    connecting: '연결 중…',
    lost: '연결 끊김',
    lostHintGathering: '센서 버튼을 다시 누르세요',
    lostHintIdle: '센서 모으기를 켜고 버튼을 누르세요',
    disconnected: '연결 해제됨',
    offline: '연결 안 됨',
  },
  time: {
    lastSeen: (rel: string) => `마지막 확인 ${rel}`,
    neverSeen: '확인 기록 없음',
    justNow: '방금 전',
    minutes: (n: number) => `${n}분 전`,
    hours: (n: number) => `${n}시간 전`,
    days: (n: number) => `${n}일 전`,
  },
  busy: {
    label: (reason: string) => `작업 중 (${reason})`,
    identify: '확인 중',
    read: '읽는 중',
    apply: '설정 적용 중',
    calibration: '보정 중',
  },
  battery: (n: number) => `배터리 ${n}%`,
  batteryLast: (n: number) => `배터리 ${n}% (마지막 값)`,
  calibration: {
    last: (rel: string) => `마지막 보정 ${rel}`,
    none: '보정 기록 없음',
  },
  snapshot: {
    last: (rel: string) => `마지막 설정 백업 ${rel}`,
  },
  nav: {
    label: '주 메뉴',
    dashboard: '대시보드',
    gather: '센서 모으기',
  },
  gather: {
    start: '센서 모으기 시작',
    stop: '모으기 끝내기',
    idleTitle: '센서 모으기를 시작하세요',
    idleBody: '시작한 뒤 센서의 버튼을 누르면 여기에 나타납니다',
    pressTitle: '센서 버튼을 누르세요',
    pressBody: '누른 센서가 아래에 나타납니다',
    pressBodyWide: '누른 센서가 오른쪽에 나타납니다',
    connecting: (n: number) => `센서 ${n}대 연결 중…`,
    pill: '모으는 중',
    listTitle: (n: number) => `이번에 모은 센서 (${n})`,
    started: '센서 모으기를 시작했습니다',
    stopped: '센서 모으기를 끝냈습니다',
  },
  sensor: {
    new: '새 센서',
    nameIt: '이름을 붙여 주세요',
    registered: '등록됨',
    defaultAlias: (n: number) => `센서 ${n}`,
    announceNew: (name: string) => `새 센서가 연결되었습니다: ${name}`,
    announceConnected: (alias: string) => `${alias} 연결됨`,
    announceLost: (alias: string) => `${alias} 연결이 끊겼습니다`,
  },
  form: {
    alias: '이름',
    site: '사이트',
    location: '위치',
    notes: '메모',
    newSite: '새 사이트…',
    newSiteName: '새 사이트 이름',
    locationPlaceholder: '예: 북쪽 벽',
    save: '저장',
    later: '나중에',
    nameAction: '이름 붙이기',
    saved: '등록했습니다',
    takenElsewhere: '다른 화면에서 이미 등록했습니다',
    required: '입력해 주세요',
    cancel: '취소',
    close: '닫기',
  },
  dash: {
    connectedN: (n: number) => `연결됨 ${n}`,
    lostN: (n: number) => `끊김 ${n}`,
    offlineN: (n: number) => `연결 안 됨 ${n}`,
    totalN: (n: number) => `전체 ${n}`,
    unregistered: '등록되지 않은 센서',
    pending: '가져온 센서 (아직 연결 안 됨)',
    pendingHint: '버튼을 누르면 자동으로 등록됩니다',
    empty: '아직 등록된 센서가 없습니다',
    gatheringCta: '모으는 중 — 보러 가기',
    summaryLabel: '센서 현황',
  },
  release: {
    all: '모두 연결 해제',
    one: '연결 해제',
    confirm: '연결을 해제하면 배터리를 아낄 수 있습니다. 다시 연결하려면 센서 버튼을 눌러야 합니다.',
    confirmGathering: '센서 모으기를 멈추고 모든 연결을 해제합니다. 다시 연결하려면 모으기를 시작하고 센서 버튼을 누르세요.',
  },
  delete: {
    action: '등록 삭제',
    confirm: '이 센서의 이름·사이트·메모를 지웁니다. 센서 설정과 보정 기록은 그대로 남습니다.',
  },
  import: {
    title: '목록 파일 가져오기 (yaml)',
    action: '가져오기',
    file: '파일',
    siteAuto: '파일 이름에서 정하기',
    done: (n: number) => `${n}개를 가져왔습니다. 버튼을 누르면 자동으로 등록됩니다`,
    none: '새로 추가된 센서가 없습니다',
  },
  conn: {
    lost: '서버와 연결이 끊겼습니다. 다시 연결하는 중…',
    down: '서버에 연결할 수 없습니다',
  },
  auth: {
    title: '접속 권한이 없습니다',
    body: '터미널에 표시된 주소나 QR 코드로 다시 접속하세요. 서버가 다시 시작되었다면 새 주소가 필요합니다.',
  },
  badge: {
    lan: 'LAN 공개 중',
    sim: '시뮬레이터',
  },
  sim: {
    title: '시뮬레이터',
    press: (n: number) => `버튼 누르기 ${n}`,
    drop: (n: number) => `끊기 ${n}`,
    pressAll: '모두 누르기',
  },
  detail: {
    comingSoon: '실시간 모니터·보정·설정 편집은 다음 버전에서 제공됩니다',
    notFound: '센서를 찾을 수 없습니다',
    back: '대시보드로',
    info: '센서 정보',
    edit: '이름과 위치',
    deviceId: 'Device ID',
    address: '주소',
    firmware: '펌웨어',
    battery: '배터리',
    light: '조도',
    lastSeen: '마지막 확인',
    lastCalibration: '마지막 보정',
    lastSnapshot: '설정 백업',
    none: '—',
  },
  notice: {
    gatherFailed: (name: string) => `연결 실패: ${name} — 버튼을 다시 눌러 주세요`,
  },
  theme: {
    system: '테마: 시스템 설정',
    light: '테마: 밝게',
    dark: '테마: 어둡게',
  },
  error: {
    unauthorized: '접속 권한이 없습니다',
    forbidden_origin: '이 주소에서는 요청할 수 없습니다',
    not_found: '대상을 찾을 수 없습니다',
    already_exists: '이미 등록되어 있습니다',
    busy: '센서가 다른 작업 중입니다',
    not_connected: '센서가 연결되어 있지 않습니다',
    invalid: '입력값을 확인해 주세요',
    invalid_request: '입력값을 확인해 주세요',
    invalid_file: (message: string) => `파일 형식이 맞지 않습니다 (${message})`,
    storage: '파일을 저장하지 못했습니다',
    internal: '알 수 없는 오류가 났습니다',
  },
} as const

export function errorText(code: ErrorCode, message: string): string {
  if (code === 'invalid_file') return t.error.invalid_file(message)
  return t.error[code]
}
