// Every Korean UI string lives here (D15, docs/GUI_API.md 10.2).
import type { ErrorCode } from './api/types'

export const t = {
  link: {
    connected: '연결됨',
    connecting: '연결 중…',
    lost: '연결 끊김',
    lostHintGathering: '센서 버튼을 다시 누르세요',
    lostHintIdle: '센서 모으기를 켜고 버튼을 누르세요',
    disconnected: '연결 해제됨',
    offline: '연결 안 됨',
  },
  time: {
    lastSeen: (rel: string) => `마지막 확인 ${rel}`,
    neverSeen: '확인 기록 없음',
    justNow: '방금 전',
    minutes: (n: number) => `${n}분 전`,
    hours: (n: number) => `${n}시간 전`,
    days: (n: number) => `${n}일 전`,
  },
  busy: {
    label: (reason: string) => `작업 중 (${reason})`,
    identify: '확인 중',
    read: '읽는 중',
    apply: '설정 적용 중',
    calibration: '보정 중',
  },
  battery: (n: number) => `배터리 ${n}%`,
  batteryLast: (n: number) => `배터리 ${n}% (마지막 값)`,
  calibration: {
    last: (rel: string) => `마지막 보정 ${rel}`,
    none: '보정 기록 없음',
  },
  snapshot: {
    last: (rel: string) => `마지막 설정 백업 ${rel}`,
  },
  nav: {
    label: '주 메뉴',
    dashboard: '대시보드',
    gather: '센서 모으기',
    monitor: '모니터',
    calibrate: '보정',
  },
  gather: {
    start: '센서 모으기 시작',
    stop: '모으기 끝내기',
    idleTitle: '센서 모으기를 시작하세요',
    idleBody: '시작한 뒤 센서의 버튼을 누르면 여기에 나타납니다',
    pressTitle: '센서 버튼을 누르세요',
    pressBody: '누른 센서가 아래에 나타납니다',
    pressBodyWide: '누른 센서가 오른쪽에 나타납니다',
    connecting: (n: number) => `센서 ${n}대 연결 중…`,
    pill: '모으는 중',
    listTitle: (n: number) => `이번에 모은 센서 (${n})`,
    started: '센서 모으기를 시작했습니다',
    stopped: '센서 모으기를 끝냈습니다',
  },
  sensor: {
    new: '새 센서',
    nameIt: '이름을 붙여 주세요',
    registered: '등록됨',
    defaultAlias: (n: number) => `센서 ${n}`,
    announceNew: (name: string) => `새 센서가 연결되었습니다: ${name}`,
    announceConnected: (alias: string) => `${alias} 연결됨`,
    announceLost: (alias: string) => `${alias} 연결이 끊겼습니다`,
  },
  form: {
    alias: '이름',
    site: '사이트',
    location: '위치',
    notes: '메모',
    newSite: '새 사이트…',
    newSiteName: '새 사이트 이름',
    locationPlaceholder: '예: 북쪽 벽',
    save: '저장',
    later: '나중에',
    nameAction: '이름 붙이기',
    saved: '등록했습니다',
    takenElsewhere: '다른 화면에서 이미 등록했습니다',
    required: '입력해 주세요',
    cancel: '취소',
    close: '닫기',
  },
  dash: {
    connectedN: (n: number) => `연결됨 ${n}`,
    lostN: (n: number) => `끊김 ${n}`,
    offlineN: (n: number) => `연결 안 됨 ${n}`,
    totalN: (n: number) => `전체 ${n}`,
    unregistered: '등록되지 않은 센서',
    pending: '가져온 센서 (아직 연결 안 됨)',
    pendingHint: '버튼을 누르면 자동으로 등록됩니다',
    empty: '아직 등록된 센서가 없습니다',
    gatheringCta: '모으는 중 — 보러 가기',
    summaryLabel: '센서 현황',
  },
  release: {
    all: '모두 연결 해제',
    one: '연결 해제',
    confirm: '연결을 해제하면 배터리를 아낄 수 있습니다. 다시 연결하려면 센서 버튼을 눌러야 합니다.',
    confirmGathering: '센서 모으기를 멈추고 모든 연결을 해제합니다. 다시 연결하려면 모으기를 시작하고 센서 버튼을 누르세요.',
    blockedByBatch: '보정이 끝난 뒤 해제할 수 있습니다',
  },
  delete: {
    action: '등록 삭제',
    confirm: '이 센서의 이름·사이트·메모를 지웁니다. 센서 설정과 보정 기록은 그대로 남습니다.',
  },
  import: {
    title: '목록 파일 가져오기 (yaml)',
    action: '가져오기',
    file: '파일',
    siteAuto: '파일 이름에서 정하기',
    done: (n: number) => `${n}개를 가져왔습니다. 버튼을 누르면 자동으로 등록됩니다`,
    none: '새로 추가된 센서가 없습니다',
  },
  conn: {
    lost: '서버와 연결이 끊겼습니다. 다시 연결하는 중…',
    down: '서버에 연결할 수 없습니다',
  },
  auth: {
    title: '접속 권한이 없습니다',
    body: '터미널에 표시된 주소나 QR 코드로 다시 접속하세요. 서버가 다시 시작되었다면 새 주소가 필요합니다.',
  },
  badge: {
    lan: 'LAN 공개 중',
    sim: '시뮬레이터',
  },
  sim: {
    title: '시뮬레이터',
    press: (n: number) => `버튼 누르기 ${n}`,
    drop: (n: number) => `끊기 ${n}`,
    pressAll: '모두 누르기',
  },
  detail: {
    comingSoon: '설정 편집은 다음 버전에서 제공됩니다',
    notFound: '센서를 찾을 수 없습니다',
    back: '대시보드로',
    info: '센서 정보',
    edit: '이름과 위치',
    deviceId: 'Device ID',
    address: '주소',
    firmware: '펌웨어',
    battery: '배터리',
    light: '조도',
    lastSeen: '마지막 확인',
    lastCalibration: '마지막 보정',
    lastSnapshot: '설정 백업',
    none: '—',
  },
  notice: {
    gatherFailed: (name: string) => `연결 실패: ${name} — 버튼을 다시 눌러 주세요`,
  },
  theme: {
    system: '테마: 시스템 설정',
    light: '테마: 밝게',
    dark: '테마: 어둡게',
  },
  error: {
    unauthorized: '접속 권한이 없습니다',
    forbidden_origin: '이 주소에서는 요청할 수 없습니다',
    not_found: '대상을 찾을 수 없습니다',
    already_exists: '이미 등록되어 있습니다',
    busy: '센서가 다른 작업 중입니다',
    not_connected: '센서가 연결되어 있지 않습니다',
    invalid: '입력값을 확인해 주세요',
    invalid_request: '입력값을 확인해 주세요',
    invalid_file: (message: string) => `파일 형식이 맞지 않습니다 (${message})`,
    storage: '파일을 저장하지 못했습니다',
    internal: '알 수 없는 오류가 났습니다',
    batch_active: '이미 진행 중인 보정이 있습니다',
  },
  // -- M3 (docs/GUI_API.md 14.8.10) --------------------------------------------------------
  monitor: {
    title: '실시간 모니터',
    pick: '볼 센서',
    all: '모두 선택',
    none: '모두 해제',
    empty: '연결된 센서가 없습니다',
    emptyHint: '센서를 모으면 여기에서 실시간 값을 볼 수 있습니다',
    noneSelected: '볼 센서를 고르세요',
    legend: '┃ = 임계값(고정) · 막대가 ┃를 넘으면 빨강 = 임계값 초과',
    legendTrigger: '트리거 숫자가 빨간색이면 센서가 재실을 감지한 것입니다',
  },
  live: {
    trigger: '재실 트리거',
    maintain: '재실 유지',
    zoneHead: '존',
    zone: (i: number, m: number) => `Z${i} · ${m.toFixed(1)} m`,
    zoneOff: '꺼짐',
    waiting: '데이터 수신 대기 중…',
    stale: '실시간 값 없음 (마지막 값)',
    calibrating: '보정 중 — 기기가 임계값을 조정하고 있습니다',
    pirOn: 'PIR 감지',
    pirOff: 'PIR 없음',
    pirUnknown: 'PIR ?',
    subOn: (n: number) => `S${n} 재실`,
    subOff: (n: number) => `S${n} 부재`,
    presenceLabel: '재실 상태',
    meterAria: (label: string, value: number, threshold: number, over: boolean) =>
      `${label} ${value}, 임계값 ${threshold}, ${over ? '초과' : '이하'}`,
    stripTitle: '실시간',
    openMonitor: '모니터에서 크게 보기',
  },
  calib: {
    title: '다중 자동 보정',
    thisSensor: '이 센서 보정',
    selectTitle: '보정할 센서를 고르세요',
    selectHint: '연결된 센서만 고를 수 있습니다',
    selectAll: '연결된 센서 모두 선택',
    next: (n: number) => `다음: 사전점검 (${n}대)`,
    notConnected: '연결되어 있지 않음',
    back: '선택 바꾸기',
    noSensors: '보정할 수 있는 센서가 없습니다',
    stepsLabel: '보정 단계',
    steps: ['센서 선택', '사전점검', '진행', '결과'] as const,
  },
  preflight: {
    title: '사전점검',
    running: (s: number) => `사람이 있는지 확인하는 중… (약 ${s}초)`,
    empty: '비어 있음',
    occupied: '아직 사람 있음',
    unknown: '확인하지 못함',
    because: (reasons: string) => `근거: ${reasons}`,
    bySub: '센서 재실',
    byPir: 'PIR 감지',
    noSamples: '값을 받지 못했습니다',
    recheck: '다시 확인',
    override: '사람이 없는 것을 확인했습니다 (경고 무시하고 시작)',
    leaveRoom: '시작 전에 방을 비워 주세요. 카운트다운이 끝나면 보정이 시작됩니다',
    warnTitle: (n: number) => `${n}대에서 아직 사람이 감지됩니다`,
    warnBody: '사람이 있으면 보정이 잘못될 수 있습니다. 방을 비우고 다시 확인하거나, N초 후 시작을 고르세요.',
  },
  start: {
    title: '시작 방법',
    now: '지금',
    delay: 'N초 후',
    at: '시각 예약',
    seconds: '초',
    secondsN: (n: number) => `${n}초`,
    atToday: (hhmm: string) => `오늘 ${hhmm}`,
    atTomorrow: (hhmm: string) => `내일 ${hhmm}`,
    goNow: '보정 시작',
    goDelay: (n: number) => `${n}초 후 보정 시작`,
    goAt: (label: string) => `${label}에 보정 예약`,
    atNote: '예약 시각까지 센서 연결을 유지합니다(배터리를 씁니다). 이 컴퓨터가 잠자기에 들어가지 않게 하세요.',
  },
  batch: {
    startingNow: '시작하는 중…',
    countdown: (mmss: string) => `${mmss} 후 보정 시작`,
    countdownSub: '후 보정 시작',
    scheduled: (hhmm: string, rel: string) => `${hhmm}에 보정 시작 · ${rel} 남음`,
    running: (done: number, total: number) => `보정 중 · ${done}/${total} 끝남`,
    done: (s: number, f: number) => `보정 끝 · 성공 ${s} · 실패 ${f}`,
    cancelled: '보정을 취소했습니다',
    remainH: (h: number, m: number) => `${h}시간 ${m}분`,
    remainM: (m: number) => `${m}분`,
    remainLt1: '1분 미만',
    cancelWaiting: '카운트다운 취소',
    cancelScheduled: '예약 취소',
    cancelRunning: '보정 취소',
    cancelConfirm: '보정을 취소하면 센서 연결을 끊어 학습을 멈춥니다. 다시 연결하려면 각 센서의 버튼을 눌러야 합니다.',
    progressNote: (mmss: string) => `막대는 예상 시간(약 ${mmss}) 기준입니다. 센서는 진행률을 알려 주지 않습니다.`,
    progressAria: (pct: number) => `약 ${pct}% (예상 시간 기준)`,
    elapsed: (elapsed: string, expected: string) => `${elapsed} / 약 ${expected}`,
    overdue: '예상보다 오래 걸리는 중',
    gatherPaused: '보정하는 동안 센서 모으기를 멈췄습니다',
    override: '재실 경고를 무시하고 시작함',
    attempt: (n: number) => `${n}번째 시도`,
    newBatch: '새 보정',
    pillWaiting: (mmss: string) => `보정 ${mmss} 후`,
    pillAt: (hhmm: string) => `보정 ${hhmm}`,
    pillRunning: (done: number, total: number) => `보정 중 ${done}/${total}`,
    sensors: '센서',
  },
  job: {
    idle: '시작 대기',
    preparing: '시작 준비 중…',
    starting: '시작하는 중…',
    learning: '학습 중',
    learningHint: '방을 비워 두세요',
    succeeded: '완료',
    saved: '보정 기록에 저장했습니다',
    noReadback: '완료 (결과값을 읽지 못함)',
    noReadbackHint: '전후 비교를 할 수 없습니다',
    notSaved: '완료 (기록 저장 실패)',
    notSavedHint: '보정은 센서에 반영되었습니다',
    busy: '시작하지 못함 (다른 작업 중)',
    busyHint: '잠시 뒤 다시 시도하세요',
    failed: '실패',
    deviceFailed: '센서가 보정 실패를 알렸습니다. 방을 비우고 다시 시도하세요',
    error: (error: string) => `오류: ${error}`,
    lostLearning: '연결 끊김 (학습 초기화됨)',
    lostBefore: '연결 끊김 (시작 전)',
    timeout: '응답 없음',
    timeoutHint: '센서가 완료를 알리지 않았습니다. 다시 시도하세요',
    cancelled: '취소됨',
    cancelledHint: '연결을 끊어 학습을 멈췄습니다. 다시 연결하려면 버튼을 누르세요',
  },
  retry: {
    title: (n: number) => `다시 시도할 센서 (${n})`,
    go: (n: number) => `다시 시도 (${n}대)`,
    reconnected: '다시 연결됨 · 다시 시도할 수 있습니다',
    whenDone: '이번 보정이 끝난 뒤 다시 시도할 수 있습니다',
    pressAgain: '버튼을 다시 누르세요',
    pressAgainGather: '센서 모으기를 켜고 버튼을 다시 누르세요',
    startGather: '센서 모으기 시작',
  },
  compare: {
    show: '전후 비교 보기',
    title: (alias: string) => `${alias} 임계값 전후`,
    zone: '존',
    cell: (before: number, after: number, delta: string) => `${before} → ${after} (${delta})`,
    none: '전후 값이 없습니다',
  },
  announce: {
    batchStarted: '보정을 시작했습니다',
    batchDone: (s: number, f: number) => `보정이 끝났습니다: 성공 ${s}, 실패 ${f}`,
    jobLost: (alias: string) => `${alias} 보정 중 연결이 끊겼습니다`,
  },
} as const

export function errorText(code: ErrorCode, message: string): string {
  if (code === 'invalid_file') return t.error.invalid_file(message)
  return t.error[code]
}
